name: Deploy to Production (Docker Compose via Direct SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy via SSH (Docker Compose)
      run: |
        echo "Starting remote Docker deployment..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash -lc "\
          set -e; \
          cd ~/nexus-digital-web; \
          git pull; \
          echo \"Pruning old docker images...\"; \
          docker image prune -f; \
          echo \"Stopping existing compose project...\"; \
          docker compose down --remove-orphans || true; \
          echo \"Force-removing legacy named containers if present...\"; \
          docker rm -f nexus-app nexus-nginx 2>/dev/null || true; \
          echo \"Starting compose (rebuild) ...\"; \
          docker compose up -d --build --remove-orphans; \
          echo \"Containers:\"; \
          docker ps; \
          echo \"Waiting for services to be healthy...\"; \
          for i in 1 2 3 4 5 6 7 8 9 10 11 12; do \
            if docker compose ps | grep -q healthy; then \
              echo \"Services are healthy!\"; \
              break; \
            fi; \
            echo \"Waiting for health checks... (attempt \$i/12)\"; \
            sleep 5; \
          done; \
          echo \"Testing health endpoint...\"; \
          curl -f --retry 5 --retry-delay 2 http://localhost/health || echo \"Health check failed, but deployment completed\"; \
          echo \"Testing seed API...\"; \
          curl -f --retry 3 --retry-delay 2 http://localhost/api/v1/pattern-seed || echo \"API check failed, but deployment completed\" \
        "'

    - name: Public HTTP smoke test
      run: |
        curl -I -L --max-time 10 https://nexus-studio-innovation.com/health || true