# .github/workflows/deploy.yml
name: Автоматичне Розгортання Nexus Digital

on:
  push:
    # Запускати при вивантаженні коду в головну гілку 'main'
    branches:
      - main
  # Дозволити ручний запуск з інтерфейсу GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Отримання коду
      uses: actions/checkout@v4

    - name: 2. Налаштування SSH для Droplet
      uses: webfactory/ssh-agent@v0.9.0
      with:
        # Використовуємо наш Секретний ключ SSH_PRIVATE_KEY
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Droplet IP (для перевірки автентичності хоста)
        known-hosts: 164.90.234.176 

    - name: 3. Розгортання та Перезапуск Сервісів
      # Виконання команд на Droplet через SSH
      run: |
        # Встановлюємо змінні
        SSH_HOST="nexususer@164.90.234.176" 
        REMOTE_DIR="/home/nexususer/nexus-digital-web"
        
        # Підключення до сервера та виконання команд
        ssh -o StrictHostKeyChecking=no $SSH_HOST << 'EOF'
          echo "Перехід до каталогу..."
          cd $REMOTE_DIR
          
          echo "Оновлення коду з GitHub..."
          git pull
          
          echo "Встановлення залежностей..."
          # Використовуємо npm install --production для оптимізації
          npm install --production
          
          # Перезапуск застосунку Node.js на порту 8080 через PM2
          echo "Перезапуск застосунку Node.js..."
          # Використовуємо команду з package.json
          npm run production
          
          # Фінальний перезапуск Nginx (Використовуємо повний шлях, дозволений NOPASSWD)
          echo "Перезапуск Nginx..."
          sudo /usr/sbin/service nginx restart
          
          echo "✅ Розгортання успішно завершено!"
        EOF