name: Автоматичне Розгортання Nexus Digital

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Отримання коду
      uses: actions/checkout@v4

    - name: 2. Налаштування SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 3. Додавання хоста до known_hosts
      run: |
        ssh-keyscan -H 164.90.234.176 >> ~/.ssh/known_hosts

    - name: 4. Тестування SSH підключення
      run: |
        ssh -o ConnectTimeout=10 nexususer@164.90.234.176 "echo 'SSH підключення успішне'"

    - name: 5. Розгортання на сервер
      run: |
        ssh nexususer@164.90.234.176 << 'EOF'
          echo "🚀 Початок розгортання..."
          
          # Перехід до директорії проєкту
          cd /home/nexususer/nexus-digital-web || exit 1
          
          # Збереження поточних змін (якщо є)
          git stash
          
          # Оновлення коду
          echo "📥 Завантаження нового коду..."
          git fetch origin
          git reset --hard origin/main
          
          # Встановлення залежностей
          echo "📦 Встановлення залежностей..."
          npm ci --production
          
          # Перезапуск додатку
          echo "🔄 Перезапуск додатку..."
          npm run production || {
            echo "❌ Помилка запуску додатку"
            exit 1
          }
          
          # Перезапуск Nginx
          echo "🌐 Перезапуск веб-сервера..."
          sudo systemctl reload nginx
          
          echo "✅ Розгортання завершено успішно!"
        EOF

    - name: 6. Перевірка статусу сайту
      run: |
        echo "🔍 Перевірка доступності сайту..."
        curl -f http://164.90.234.176 || echo "⚠️ Сайт поки недоступний, але розгортання завершено"
