name: Deploy to Production (Docker Compose via Direct SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy via SSH (Docker Compose)
      run: |
        echo "Starting remote Docker deployment..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash -lc "\
          set -euo pipefail; \
          cd ~/nexus-digital-web; \
          git pull; \
          echo \"Pruning old docker images...\"; \
          docker image prune -f; \
          echo \"Stopping existing compose project...\"; \
          docker compose down --remove-orphans || true; \
          echo \"Force-removing legacy named containers if present...\"; \
          docker rm -f nexus-app nexus-nginx 2>/dev/null || true; \
          echo \"Starting compose (rebuild) ...\"; \
          docker compose up -d --build --remove-orphans; \
          echo \"Containers:\"; \
          docker ps; \
          echo \"Waiting for app health...\"; \
          sleep 5; \
          curl -fsSL http://localhost/health; \
          echo \"\\nSeed API:\"; \
          curl -fsSL http://localhost/api/v1/pattern-seed \
        "'

    - name: Public HTTP smoke test
      run: |
        curl -I -L --max-time 10 https://nexus-studio-innovation.com/health || true