name: Автоматичне Розгортання Nexus Digital

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: 1. Отримання коду
      uses: actions/checkout@v4

    - name: 2. Налаштування SSH ключа
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 3. Додавання сервера до known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 164.90.234.176 >> ~/.ssh/known_hosts

    - name: 4. Тестування SSH підключення
      run: |
        echo "🔍 Тестування SSH підключення..."
        ssh -o ConnectTimeout=30 -o BatchMode=yes nexususer@164.90.234.176 "echo 'SSH підключення успішне'"

    - name: 5. Розгортання на сервер
      run: |
        echo "🚀 Початок розгортання..."
        ssh -o ConnectTimeout=30 nexususer@164.90.234.176 'bash -s' << 'ENDSSH'
          set -e  # Зупинити виконання при першій помилці
          
          echo "📂 Перевірка директорії проєкту..."
          PROJECT_DIR="/home/nexususer/nexus-digital-web"
          
          # Створити директорію якщо не існує
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "📁 Створення директорії проєкту..."
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"
            git clone https://github.com/Danylo-Molianko/nexus-digital.git .
          else
            echo "📥 Оновлення існуючого проєкту..."
            cd "$PROJECT_DIR"
            
            # Збереження локальних змін
            if [ -n "$(git status --porcelain)" ]; then
              echo "💾 Збереження локальних змін..."
              git stash
            fi
            
            # Оновлення з GitHub
            git fetch origin
            git reset --hard origin/main
          fi
          
          echo "📦 Перевірка package.json..."
          if [ ! -f "package.json" ]; then
            echo "📝 Створення package.json..."
            cat > package.json << 'EOF'
        {
          "name": "nexus-digital",
          "version": "1.0.0",
          "description": "Nexus Digital - AI & Web Development",
          "main": "server.js",
          "scripts": {
            "start": "node server.js",
            "production": "pm2 restart nexus-digital || pm2 start server.js --name nexus-digital",
            "stop": "pm2 stop nexus-digital || true"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }
        EOF
          fi
          
          echo "🖥️ Перевірка server.js..."
          if [ ! -f "server.js" ]; then
            echo "📝 Створення server.js..."
            cat > server.js << 'EOF'
        const express = require('express');
        const path = require('path');
        const app = express();
        const PORT = process.env.PORT || 8080;
        
        console.log('🚀 Запуск Nexus Digital сервера...');
        
        app.use(express.static(path.join(__dirname, 'public')));
        app.use('/assets', express.static(path.join(__dirname, 'assets')));
        
        app.get('/', (req, res) => {
            res.sendFile(path.join(__dirname, 'public', 'index.html'));
        });
        
        app.use((req, res) => {
            res.status(404).sendFile(path.join(__dirname, 'public', 'index.html'));
        });
        
        app.listen(PORT, '0.0.0.0', () => {
            console.log(`✅ Сервер запущено на порту ${PORT}`);
        });
        EOF
          fi
          
          echo "📦 Встановлення залежностей..."
          if command -v npm >/dev/null 2>&1; then
            npm install --production
          else
            echo "❌ npm не знайдено, встановлюйте Node.js"
            exit 1
          fi
          
          echo "🔄 Запуск/перезапуск сервера..."
          if command -v pm2 >/dev/null 2>&1; then
            npm run production
            echo "✅ PM2 сервер запущено"
          else
            echo "⚠️ PM2 не знайдено, запуск через nohup..."
            pkill -f "node server.js" || true
            nohup node server.js > server.log 2>&1 &
            echo "✅ Сервер запущено в фоновому режимі"
          fi
          
          echo "🌐 Перезапуск Nginx..."
          if command -v nginx >/dev/null 2>&1; then
            sudo systemctl reload nginx || echo "⚠️ Nginx перезапуск не вдався"
          else
            echo "⚠️ Nginx не знайдено"
          fi
          
          echo "✅ Розгортання завершено успішно!"
        ENDSSH

    - name: 6. Перевірка статусу
      run: |
        echo "🔍 Перевірка доступності сайту..."
        sleep 5
        if curl -f -s http://164.90.234.176 > /dev/null; then
          echo "✅ Сайт доступний!"
        else
          echo "⚠️ Сайт поки недоступний, але розгортання завершено"
        fi
