name: Автоматичне Розгортання Nexus Digital

on:
  push:
    # Запускати при вивантаженні коду в головну гілку 'main'
    branches:
      - main
  # Дозволити ручний запуск з інтерфейсу GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Отримання коду
      uses: actions/checkout@v4

    - name: 2. Налаштування SSH для Droplet
      uses: webfactory/ssh-agent@v0.9.0
      with:
        # Використовуємо наш Секретний ключ SSH_PRIVATE_KEY
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Droplet IP (для перевірки автентичності хоста)
        known-hosts: 164.90.234.176 

    - name: 3. Розгортання та Перезапуск Сервісів
      # Виконання команд на Droplet через SSH
      run: |
        # Встановлюємо змінні
        SSH_HOST="nexususer@164.90.234.176" 
        REMOTE_DIR="/home/nexususer/nexus-digital-web"
        
        # Підключення до сервера та виконання команд
        ssh -o StrictHostKeyChecking=no $SSH_HOST << 'EOF'
          echo "Перехід до каталогу..."
          cd $REMOTE_DIR
          
          echo "Оновлення коду з GitHub..."
          git pull
          
          echo "Встановлення залежностей..."
          # Використовуємо npm install --production для оптимізації
          npm install --production
          
          # Перезапуск застосунку Node.js на порту 8080 через PM2
          echo "Перезапуск застосунку Node.js..."
          # Використовуємо команду з package.json
          npm run production
          
          # Фінальний перезапуск Nginx (Використовуємо повний шлях, дозволений NOPASSWD)
          echo "Перезапуск Nginx..."
          sudo /usr/sbin/service nginx restart
          
          echo "✅ Розгортання успішно завершено!"
        EOF
            log_info "Створення директорії проєкту..."
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"
            
            # Ініціалізація git репозиторію
            if ! git clone https://github.com/Danylo-Molianko/nexus-digital.git . 2>/dev/null; then
              log_warn "Клонування не вдалося, ініціалізуємо порожній репозиторій..."
              git init
              git remote add origin https://github.com/Danylo-Molianko/nexus-digital.git
            fi
          else
            log_info "Оновлення існуючого проєкту..."
            cd "$PROJECT_DIR"
            
            # Збереження локальних змін
            if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
              log_info "Збереження локальних змін..."
              git stash || log_warn "Не вдалося зберегти зміни"
            fi
            
            # Оновлення з GitHub
            log_info "Завантаження останніх змін..."
            git fetch origin main || log_warn "Fetch не вдався"
            git reset --hard origin/main || git reset --hard HEAD
          fi
          
          # Створення package.json якщо не існує
          if [ ! -f "package.json" ]; then
            log_info "Створення package.json..."
            cat > package.json << 'PACKAGE_JSON'
        {
          "name": "nexus-digital",
          "version": "1.0.0",
          "description": "Nexus Digital Website",
          "main": "server.js",
          "scripts": {
            "start": "node server.js",
            "production": "pm2 restart nexus-digital || pm2 start server.js --name nexus-digital",
            "stop": "pm2 stop nexus-digital || true"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }
        PACKAGE_JSON
          fi
          
          # Створення server.js якщо не існує
          if [ ! -f "server.js" ]; then
            log_info "Створення server.js..."
            cat > server.js << 'SERVER_JS'
        const express = require('express');
        const path = require('path');
        const app = express();
        const PORT = process.env.PORT || 8080;
        
        console.log('🚀 Запуск Nexus Digital...');
        
        // Статичні файли
        app.use(express.static(path.join(__dirname, 'public')));
        app.use('/assets', express.static(path.join(__dirname, 'assets')));
        
        // Основний маршрут
        app.get('/', (req, res) => {
            const indexPath = path.join(__dirname, 'public', 'index.html');
            res.sendFile(indexPath, (err) => {
                if (err) {
                    console.error('Помилка відправки файлу:', err);
                    res.status(500).send('Помилка сервера');
                }
            });
        });
        
        // Обробка всіх інших маршрутів
        app.get('*', (req, res) => {
            const indexPath = path.join(__dirname, 'public', 'index.html');
            res.sendFile(indexPath, (err) => {
                if (err) {
                    res.status(404).send('Сторінка не знайдена');
                }
            });
        });
        
        // Запуск сервера
        app.listen(PORT, '0.0.0.0', () => {
            console.log(`✅ Сервер запущено на порту ${PORT}`);
            console.log(`🌐 Доступно: http://localhost:${PORT}`);
        });
        SERVER_JS
          fi
          
          # Встановлення Node.js якщо не встановлено
          if ! command -v node >/dev/null 2>&1; then
            log_warn "Node.js не знайдено, встановлюємо..."
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          
          # Встановлення залежностей
          log_info "Встановлення залежностей..."
          if command -v npm >/dev/null 2>&1; then
            npm install --production --no-audit --no-fund
          else
            log_error "npm не знайдено"
            exit 1
          fi
          
          # Встановлення PM2 якщо не встановлено
          if ! command -v pm2 >/dev/null 2>&1; then
            log_info "Встановлення PM2..."
            sudo npm install -g pm2
          fi
          
          # Запуск/перезапуск сервера
          log_info "Запуск сервера..."
          if pm2 describe nexus-digital >/dev/null 2>&1; then
            log_info "Перезапуск існуючого додатку..."
            pm2 restart nexus-digital
          else
            log_info "Запуск нового додатку..."
            pm2 start server.js --name nexus-digital
          fi
          
          # Збереження конфігурації PM2
          pm2 save
          pm2 startup | tail -1 | sudo sh || log_warn "PM2 startup не налаштовано"
          
          # Перезапуск Nginx якщо встановлено
          if command -v nginx >/dev/null 2>&1; then
            log_info "Перезапуск Nginx..."
            sudo systemctl reload nginx || log_warn "Nginx reload не вдався"
          fi
          
          # Перевірка статусу
          log_info "Перевірка статусу додатку..."
          if pm2 describe nexus-digital | grep -q "online"; then
            log_info "✅ Додаток працює онлайн"
          else
            log_warn "⚠️ Додаток може працювати не стабільно"
          fi
          
          log_info "🎉 Розгортання завершено успішно!"
        ENDSSH

    - name: 6. Перевірка статусу сайту
      run: |
        echo "🔍 Перевірка доступності сайту..."
        sleep 10
        
        # Перевірка з тайм-аутом
        if timeout 30 bash -c 'until curl -f -s http://164.90.234.176 >/dev/null; do sleep 2; done'; then
          echo "✅ Сайт доступний за адресою: http://164.90.234.176"
        else
          echo "⚠️ Сайт поки недоступний, але розгортання завершено"
          echo "Перевірте логи сервера вручну"
        fi

    - name: 7. Показати статус PM2
      run: |
        echo "📊 Статус додатків на сервері:"
        ssh nexususer@164.90.234.176 "pm2 list || echo 'PM2 недоступний'"
      continue-on-error: true
