name: Deploy to Production

on:
  push:
    branches:
      - main # Або 'master', залежно від вашої головної гілки

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd ~/nexus-digital-web
          git pull
          docker compose down
          docker compose up -d --build
          echo "Pruning old docker images..."
          docker image prune -f