name: Build and Deploy Nexus Studio (Production - Direct SSH/SCP + Debug)

on:
  push:
    branches:
      - main # Запускати тільки при push в main

jobs:
  # --- 1. РОБОТА: ЗБІРКА (Без змін) ---
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project (Production)
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 1

  # --- 2. РОБОТА: РОЗГОРТАННЯ (DEPLOYMENT - НОВА СТРАТЕГІЯ) ---
  deploy:
    needs: build # Запускається тільки після успішної збірки
    runs-on: ubuntu-latest

    steps:
    # [НОВИЙ ДІАГНОСТИЧНИЙ КРОК] Перевіряємо доступ до секрету
    - name: "Debug: Print SSH_HOST Secret"
      run: |
        echo "Attempting to print host: [${{ secrets.SSH_HOST }}]"

    - name: Download production artifacts
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: dist/ # Завантажуємо у папку 'dist'

    - name: ⚙️ Setup SSH Key
      # [НОВИЙ КРОК] Налаштовуємо SSH вручну, щоб гарантувати доступ
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa # Кладемо ключ з секретів
        chmod 600 ~/.ssh/id_rsa # Встановлюємо правильні дозволи
        ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts # Додаємо хост до відомих

    - name: 🚀 Deploy Files via SCP (Direct)
      # [НОВИЙ КРОК] Використовуємо базову команду scp
      run: |
        echo "Copying build files to server..."
        scp -r dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}
        echo "✅ Files copied successfully!"

    - name: 🔄 Restart Production Server (Direct SSH)
      # [НОВИЙ КРОК] Використовуємо базову команду ssh для перезапуску
      run: |
        echo "Connecting to server to restart application..."
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Команди, що виконаються на сервері
          echo "Changing to project directory..."
          cd ${{ secrets.PROJECT_DIR }}
          
          echo "Restarting application with pm2..."
          # export PATH=$PATH:/home/nexususer/.nvm/versions/node/v18.18.2/bin # Якщо pm2 не в PATH
          pm2 restart nexus_app
          
          echo "✅ Application restarted successfully!"
        EOF # Кінець команд для сервера
        strip_components: 1 # Не створювати 'dist/dist', а класти файли прямо
        overwrite: true

    - name: 🔄 Restart Production Server
      # [ІДЕАЛЬНИЙ КРОК 2: ПЕРЕЗАПУСК]
      # Це найважливіший крок. Ми перезапускаємо процес 'node'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Переходимо в папку проекту на сервері
          cd ${{ secrets.PROJECT_DIR }}
          
          # Ми припускаємо, що процес керується 'pm2'
          # і його назва 'nexus_app' (як у Nginx-конфігу)
          echo "Restarting application server..."
          
          # Вказуємо шлях до pm2. 
          # Цей шлях може знадобитись, якщо pm2 не в глобальному $PATH
          # export PATH=$PATH:/home/nexususer/.nvm/versions/node/v18.18.2/bin
          
          # Перезапускаємо процес
          pm2 restart nexus_app
          
          echo "✅ Production Deployment Successful!"