name: Build and Deploy Nexus Studio (Production)

on:
  push:
    branches:
      - main # Запускати тільки при push в main

jobs:
  # --- 1. РОБОТА: ЗБІРКА ---
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project (Production)
      run: npm run build

    - name: Archive production artifacts
      # [ІДЕАЛЬНИЙ КРОК] Зберігаємо 'dist' для наступної роботи
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 1

  # --- 2. РОБОТА: РОЗГОРТАННЯ (DEPLOYMENT) ---
  deploy:
    needs: build # Запускається тільки після успішної збірки
    runs-on: ubuntu-latest

    steps:
    - name: Download production artifacts
      # Завантажуємо 'dist', який зібрала попередня робота
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: dist/

    - name: 🚀 Deploy Files via SCP
      # [ІДЕАЛЬНИЙ КРОК 1: КОПІЮВАННЯ ФАЙЛІВ]
      # Використовуємо 'scp' для копіювання наших артефактів
      # у НОВУ папку 'dist' на сервері
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "dist/*" # Копіюємо вміст 'dist'
        target: "${{ secrets.TARGET_DIR }}" # У цільову папку
        strip_components: 1 # Не створювати 'dist/dist', а класти файли прямо
        overwrite: true

    - name: 🔄 Restart Production Server
      # [ІДЕАЛЬНИЙ КРОК 2: ПЕРЕЗАПУСК]
      # Це найважливіший крок. Ми перезапускаємо процес 'node'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Переходимо в папку проекту на сервері
          cd ${{ secrets.PROJECT_DIR }}
          
          # Ми припускаємо, що процес керується 'pm2'
          # і його назва 'nexus_app' (як у Nginx-конфігу)
          echo "Restarting application server..."
          
          # Вказуємо шлях до pm2. 
          # Цей шлях може знадобитись, якщо pm2 не в глобальному $PATH
          # export PATH=$PATH:/home/nexususer/.nvm/versions/node/v18.18.2/bin
          
          # Перезапускаємо процес
          pm2 restart nexus_app
          
          echo "✅ Production Deployment Successful!"